name: Build and Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.9.0 --activate

      - name: Install Dependencies and Build
        run: make build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./storybook-static # or your build output directory
