name: Lint checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Unit tests
        run: make test

      - name: ESlint
        run: bun run lint

      - name: Storybook
        run: bun run build-storybook
