name: Lint checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.9.0 --activate

      - name: Unit tests
        run: make test

      - name: ESlint
        run: pnpm run lint

      - name: Storybook
        run: pnpm run build-storybook
