name: Update Flow Icons

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Enable corepack (pnpm support)
        run: corepack enable
      - name: Set `npm` to use `pnpm`
        run: npm config set engine-strict true
      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }}" > packages/flow-icons/.env
          echo "FILE_KEY=${{ secrets.FILE_KEY }}" >> packages/flow-icons/.env

      - name: Run icon download script
        working-directory: packages/flow-icons
        run: pnpm run download-icons

      - name: Check for changes
        id: git-status
        run: |
          git status --porcelain
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Get current package version
        if: env.changes == 'true'
        id: version
        working-directory: packages/flow-icons
        run: echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Bump package version (minor)
        if: env.changes == 'true'
        working-directory: packages/flow-icons
        run: |
          NEW_VERSION=$(jq -r '.version' package.json | awk -F. '{$2+=1; $3=0; print $1"."$2"."$3}')
          jq --arg version "$NEW_VERSION" '.version = $version' package.json > temp.json && mv temp.json package.json
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update CHANGELOGS.md
        if: env.changes == 'true'
        run: |
          echo "## Version $NEW_VERSION - $(date +'%Y-%m-%d')" >> packages/flow-icons/CHANGELOGS.md
          echo "- Updated icons from Figma" >> packages/flow-icons/CHANGELOGS.md
          echo "" >> packages/flow-icons/CHANGELOGS.md

      - name: Commit and push changes
        if: env.changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run prettify
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "vikas@nonfx.com"
          git add -A
          git commit -m "chore(flow-icons): update icons, bump version, and update CHANGELOGS.md" || echo "No changes to commit"
          git push origin main
