name: Update Flow Icons

on:
  workflow_dispatch:

jobs:
  update-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable corepack (pnpm support)
        run: corepack enable
      - name: Set `npm` to use `pnpm`
        run: npm config set engine-strict true
      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create .env file
        run: |
          echo "FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }}" > packages/flow-icons/.env
          echo "FILE_KEY=${{ secrets.FILE_KEY }}" >> packages/flow-icons/.env

      - name: Run icon download script
        working-directory: packages/flow-icons
        run: pnpm exec download-icons

      - name: Check for changes
        id: git-status
        run: |
          git status --porcelain
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Get current package version
        if: env.changes == 'true'
        id: version
        working-directory: packages/flow-icons
        run: echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Bump package version (minor)
        if: env.changes == 'true'
        working-directory: packages/flow-icons
        run: pnpm version minor --no-git-tag-version

      - name: Update CHANGELOGS.md
        if: env.changes == 'true'
        run: |
          echo "## Version $NEW_VERSION - $(date +'%Y-%m-%d')" >> packages/flow-icons/CHANGELOGS.md
          echo "- Updated icons from Figma" >> packages/flow-icons/CHANGELOGS.md
          echo "" >> packages/flow-icons/CHANGELOGS.md

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/flow-icons
          git commit -m "chore(flow-icons): update icons, bump version to $NEW_VERSION, and update CHANGELOGS.md"
          git push origin main
