name: Test and Release

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  publish_to_npm:
    name: Publishing to npm registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAGES_TOKEN }}

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 20.x

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.9.0 --activate

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%B %d, %Y')"

      - name: extract-changelogs
        if: steps.changesets.outputs.published == 'true'
        id: change-logs
        uses: vikas-cldcvr/extract-changelogs@v0.1.1
        with:
          released-package-versions: ${{ steps.changesets.outputs.publishedPackages }}
          changelog-files-config: |
            {
              "@nonfx/flow-log":"packages/flow-log/CHANGELOG.md",
              "@nonfx/flow-code-editor":"packages/flow-code-editor/CHANGELOG.md",
              "@nonfx/flow-md-editor":"packages/flow-md-editor/CHANGELOG.md",
              "@nonfx/flow-text-editor":"packages/flow-text-editor/CHANGELOG.md",
              "@nonfx/flow-core":"packages/flow-core/CHANGELOG.md",
              "@nonfx/flow-table":"packages/flow-table/CHANGELOG.md",
              "@nonfx/flow-core-config":"packages/flow-core-config/CHANGELOG.md",
              "@nonfx/flow-form-builder":"packages/flow-form-builder/CHANGELOG.md",
              "@nonfx/flow-lineage":"packages/flow-lineage/CHANGELOG.md",
              "@nonfx/flow-dashboard":"packages/flow-dashboard/CHANGELOG.md",
              "@nonfx/custom-elements-manifest-to-types":"packages/custom-elements-manifest-to-types/CHANGELOG.md"
            }

      - name: Send Slack Notification
        if: steps.changesets.outputs.published == 'true'
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Updates",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":mega: Flow Announcement"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "text": "*${{ steps.date.outputs.date }}* | New Release Alert",
                      "type": "mrkdwn"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hello everyone!\nPlease find below the changelogs"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(steps.change-logs.outputs.changeLogs) }}
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
